# Generated by Django 5.2.6 on 2025-09-25 18:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(max_length=50)),
                ('kcpe_marks', models.IntegerField(blank=True, null=True)),
                ('stream', models.CharField(max_length=50)),
                ('form_level', models.IntegerField(choices=[(1, 'Form 1'), (2, 'Form 2'), (3, 'Form 3'), (4, 'Form 4')])),
                ('phone_contact', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the international format: '+2547XXXXXXXX'.", regex='^\\+?254\\d{9}$')])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school')),
                ('subjects', models.ManyToManyField(blank=True, related_name='students', to='subjects.subject')),
            ],
            options={
                'unique_together': {('school', 'admission_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentAdvancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_form_level', models.IntegerField()),
                ('to_form_level', models.IntegerField()),
                ('advancement_year', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advancements', to='school.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advancements', to='students.student')),
            ],
        ),
    ]
