# Generated by Django 5.2.6 on 2025-09-20 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_subjects',
            field=models.ManyToManyField(related_name='enrolled_students', through='subjects.StudentSubjectEnrollment', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='studentadvancement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentadvancement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advancements', to='students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.subjectcategory'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grading_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.gradingsystem'),
        ),
        migrations.AddField(
            model_name='classsubjectavailability',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject'),
        ),
        migrations.AddField(
            model_name='subjectpaperratio',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subjectpaper'),
        ),
        migrations.AddField(
            model_name='subjectpaperratio',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='papers',
            field=models.ManyToManyField(through='students.SubjectPaperRatio', to='students.subjectpaper'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('form_level', 'stream', 'admission_number')},
        ),
        migrations.AlterUniqueTogether(
            name='studentadvancement',
            unique_together={('student', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubjectavailability',
            unique_together={('form_level', 'stream', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectpaperratio',
            unique_together={('subject', 'paper')},
        ),
    ]
