[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.6",
    "django-bootstrap4>=25.2",
    "djangorestframework>=3.16.1",
    "pillow>=11.3.0",
    "reportlab>=4.4.4",
]
