# Generated by Django 5.2.6 on 2025-09-29 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="subjects.subject",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="formlevel",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_levels",
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="form_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streams",
                to="school.formlevel",
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streams",
                to="school.school",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="formlevel",
            unique_together={("school", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="stream",
            unique_together={("school", "form_level", "name")},
        ),
    ]
