# Generated by Django 5.2.6 on 2025-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formlevel",
            name="number",
            field=models.IntegerField(
                choices=[(1, "Form 1"), (2, "Form 2"), (3, "Form 3"), (4, "Form 4")]
            ),
        ),
    ]
