# Generated by Django 5.2.6 on 2025-09-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="school_code",
            field=models.CharField(
                blank=True,
                help_text="Unique code for student authentication",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
