# Generated by Django 5.2.6 on 2025-09-19 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('MID_YEAR', 'Mid Year Exam'), ('END_TERM', 'End Term Exam'), ('AVERAGE', 'Average Exam'), ('CAT', 'Continuous Assessment Test')], max_length=20)),
                ('year', models.IntegerField()),
                ('term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('form_level', models.IntegerField(choices=[(1, 'Form 1'), (2, 'Form 2'), (3, 'Form 3'), (4, 'Form 4')])),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', '-term', 'form_level'],
                'unique_together': {('name', 'exam_type', 'year', 'term', 'form_level')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(blank=True, choices=[('A', 'A (80-100)'), ('A-', 'A- (75-79)'), ('B+', 'B+ (70-74)'), ('B', 'B (65-69)'), ('B-', 'B- (60-64)'), ('C+', 'C+ (55-59)'), ('C', 'C (50-54)'), ('C-', 'C- (45-49)'), ('D+', 'D+ (40-44)'), ('D', 'D (35-39)'), ('D-', 'D- (30-34)'), ('E', 'E (0-29)'), ('X', 'X (Absent)')], max_length=2)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('deviation', models.IntegerField(blank=True, null=True)),
                ('rank_in_subject', models.IntegerField(blank=True, null=True)),
                ('total_students_in_subject', models.IntegerField(blank=True, null=True)),
                ('date_entered', models.DateTimeField(default=django.utils.timezone.now)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
            options={
                'ordering': ['exam', 'student', 'subject'],
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentExamSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('mean_marks', models.FloatField(default=0.0)),
                ('mean_grade', models.CharField(blank=True, max_length=2)),
                ('stream_position', models.IntegerField(blank=True, null=True)),
                ('overall_position', models.IntegerField(blank=True, null=True)),
                ('total_students_in_stream', models.IntegerField(blank=True, null=True)),
                ('total_students_overall', models.IntegerField(blank=True, null=True)),
                ('subjects_count', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_summaries', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_summaries', to='students.student')),
            ],
            options={
                'ordering': ['exam', '-total_marks'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
