# Generated by Django 5.2.6 on 2025-09-27 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
        ("subjects", "0002_remove_subjectpaper_contribution_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradingsystem",
            name="subject_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grading_systems",
                to="subjects.subjectcategory",
            ),
        ),
    ]
