# Generated by Django 5.2.6 on 2025-09-29 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("school", "0002_initial"),
        ("students", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="participating_forms",
            field=models.ManyToManyField(
                blank=True, related_name="exams", to="school.formlevel"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_results",
                to="exams.exam",
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_results",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_results",
                to="subjects.subject",
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gradingsystem",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gradingsystem",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grading_systems",
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="gradingsystem",
            name="subject_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grading_systems",
                to="subjects.subjectcategory",
            ),
        ),
        migrations.AddField(
            model_name="gradingrange",
            name="grading_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grading_ranges",
                to="exams.gradingsystem",
            ),
        ),
        migrations.AddField(
            model_name="paperresult",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_results",
                to="exams.exam",
            ),
        ),
        migrations.AddField(
            model_name="paperresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_results",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="paperresult",
            name="subject_paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_results",
                to="subjects.subjectpaper",
            ),
        ),
        migrations.AddField(
            model_name="studentexamsummary",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_summaries",
                to="exams.exam",
            ),
        ),
        migrations.AddField(
            model_name="studentexamsummary",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_summaries",
                to="students.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exam",
            unique_together={("school", "name", "form_level", "year", "term")},
        ),
        migrations.AlterUniqueTogether(
            name="examresult",
            unique_together={("exam", "student", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="gradingrange",
            unique_together={("grading_system", "min_marks", "max_marks")},
        ),
        migrations.AlterUniqueTogether(
            name="paperresult",
            unique_together={("exam", "student", "subject_paper")},
        ),
        migrations.AlterUniqueTogether(
            name="studentexamsummary",
            unique_together={("exam", "student")},
        ),
    ]
