# Generated by Django 5.2.6 on 2025-09-20 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='participating_forms',
            field=models.ManyToManyField(help_text='Select which forms will participate in this exam', related_name='exams', to='exams.formlevel'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingrange',
            name='grading_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='exams.gradingsystem'),
        ),
        migrations.AddField(
            model_name='paperresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paperresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
        ),
        migrations.AddField(
            model_name='paperresult',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subjectpaper'),
        ),
        migrations.AddField(
            model_name='paperresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='paperresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject'),
        ),
        migrations.AddField(
            model_name='studentexamsummary',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_summaries', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='studentexamsummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_summaries', to='students.student'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_systems', to='exams.subjectcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='gradingrange',
            unique_together={('grading_system', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='paperresult',
            unique_together={('exam', 'student', 'subject', 'paper')},
        ),
        migrations.AlterUniqueTogether(
            name='studentexamsummary',
            unique_together={('exam', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='gradingsystem',
            unique_together={('category', 'name')},
        ),
    ]
