# Generated by Django 5.2.6 on 2025-09-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_alter_gradingsystem_subject_category"),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_consolidated_exam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_kcse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_ordinary_exam",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_year_average",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="participating_forms",
            field=models.ManyToManyField(
                blank=True, related_name="exams", to="school.formlevel"
            ),
        ),
    ]
