# Generated by Django 5.2.6 on 2025-09-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamsummary',
            name='mean_points',
            field=models.FloatField(default=0.0),
        ),
    ]
