# Generated by Django 5.2.6 on 2025-10-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradingsystem",
            name="is_positioning_system",
            field=models.BooleanField(
                default=False,
                help_text="If true, this system is used for student positioning/ranking based on position numbers",
            ),
        ),
    ]
