# Generated by Django 5.2.6 on 2025-09-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_exam_is_active_exam_is_consolidated_exam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentexamsummary",
            name="best_of_seven_marks",
            field=models.IntegerField(
                blank=True, help_text="Total marks from best 7 subjects", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentexamsummary",
            name="best_of_seven_points",
            field=models.IntegerField(
                blank=True, help_text="Total points from best 7 subjects", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentexamsummary",
            name="excluded_subjects",
            field=models.JSONField(
                default=list,
                help_text="List of subject IDs excluded from best 7 calculation",
            ),
        ),
        migrations.AddField(
            model_name="studentexamsummary",
            name="subjects_count",
            field=models.IntegerField(
                default=0, help_text="Total number of subjects taken"
            ),
        ),
    ]
