# Generated by Django 5.2.6 on 2025-09-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_report_cover', models.BooleanField(default=True)),
                ('show_subject_grades', models.BooleanField(default=True)),
                ('show_student_remarks', models.BooleanField(default=True)),
                ('show_stream_rank', models.BooleanField(default=True)),
                ('show_overall_rank', models.BooleanField(default=True)),
                ('show_teacher_initials', models.BooleanField(default=True)),
                ('show_watermark', models.BooleanField(default=True)),
                ('show_school_fees_layout', models.BooleanField(default=False)),
                ('closing_date', models.CharField(blank=True, max_length=50)),
                ('next_term_begins', models.CharField(blank=True, max_length=50)),
                ('class_teacher_remarks', models.TextField(blank=True)),
                ('principal_remarks', models.TextField(blank=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_settings', to='school.school')),
            ],
        ),
    ]
