# Generated by Django 5.2.6 on 2025-09-20 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_level', models.IntegerField(blank=True, choices=[(1, 'Form 1'), (2, 'Form 2'), (3, 'Form 3'), (4, 'Form 4')], null=True)),
                ('stream', models.CharField(blank=True, max_length=20, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_generated'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('STUDENT_REPORT', 'Individual Student Report'), ('CLASS_MERIT_LIST', 'Class Merit List'), ('SUBJECT_ANALYSIS', 'Subject Analysis Report'), ('TEACHER_REPORT', 'Teacher Performance Report')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('EXCELLENT', 'Excellent performance. Keep it up!'), ('GOOD', 'Good work. You can do better.'), ('AVERAGE', 'Average performance. Put more effort.'), ('BELOW_AVERAGE', 'Below average performance. You have the potential to do better.'), ('WEAK', 'Weak but has potential'), ('VERY_WEAK', 'Very weak. Needs serious improvement.')], max_length=20)),
                ('custom_comment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='exams.exam')),
            ],
        ),
    ]
