# Generated by Django 5.2.6 on 2025-09-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsettings",
            name="school",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_settings",
                to="school.school",
            ),
        ),
    ]
