# Generated by Django 5.2.6 on 2025-09-27 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectpaper",
            name="contribution_percentage",
        ),
        migrations.AddField(
            model_name="subjectpaper",
            name="student_contribution_marks",
            field=models.IntegerField(
                default=50,
                help_text="Student contribution marks to the final subject score.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
