# Generated by Django 5.2.6 on 2025-09-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_school_school_code"),
        ("subjects", "0002_remove_subjectpaper_contribution_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="form_levels",
            field=models.ManyToManyField(
                blank=True, related_name="subjects", to="school.formlevel"
            ),
        ),
    ]
